---
- name: Install Tomcat at pet-clinic user
  get_url:
            url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.tar.gz
            dest: /home/pet-clinic/
- name: Extract Tomcat tar file
  unarchive:
            src: /home/pet-clinic/apache-tomcat-10.1.24.tar.gz
            dest: /home/pet-clinic/
            remote_src: yes
- name: configure tomcat to have access to its deployment manager
  lineinfile:
        path: /home/pet-clinic/apache-tomcat-10.1.24/conf/tomcat-users.xml 
        insertbefore: '</tomcat-users>'
        line: '<role rolename="manager-gui"/> <user username="tomcat" password="s3cret" roles="manager-gui"/>'
    

- name: make application running on port 9090
  lineinfile:
        path: /home/pet-clinic/apache-tomcat-10.1.24/conf/server.xml
        regexp: '<Connector port="8080"'
        line: '<Connector port="9090"'
- name: high availability of Tomcat server
  script: 
      - cp -avr /home/pet-clinic/apache-tomcat-10.1.24 /home/pet-clinic/instance1
      - cp -avr /home/pet-clinic/apache-tomcat-10.1.24 /home/pet-clinic/instance2

- name: remove instance directories
  script:
      - rm -rf /home/pet-clinic/instance1/bin/
      - rm -rf /home/pet-clinic/instance2/bin/
      - rm -rf /home/pet-clinic/instance1/lib/
      - rm -rf /home/pet-clinic/instance2/lib/
- name: configure instance1 to run on port 9091
  lineinfile:
        path: /home/pet-clinic/instance1/conf/server.xml
        regexp: '<Connector port="9090"'
        line: '<Connector port="9091"'
- name: configure instance2 to run on port 9092
  lineinfile:
        path: /home/pet-clinic/instance2/conf/server.xml
        regexp: '<Connector port="9090"'
        line: '<Connector port="9092"'
- name: configure instance1 server port
  lineinfile:
        path: /home/pet-clinic/instance1/conf/server.xml
        regexp: '<Server port="8005"'
        line: '<Server port="8105"'
- name: configure instance2 server port 
  lineinfile:
        path: /home/pet-clinic/instance2/conf/server.xml
        regexp: '<Server port="8005"'
        line: '<Server port="8205"'
- name: start instance1
  command: /home/pet-clinic/startup1.sh
- name: start instance2 
  command: /home/pet-clinic/startup2.sh